# container = servis
services:
# containerların listesi
  app:
   # docker build -t ... otomatikleşmiş hali
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=development
    restart: unless-stopped
